<?php
// artisan tinker command to insert penilaians
// Run: php artisan tinker < insert_penilaian.php

use App\Models\Peserta;
use App\Models\Penilaian;
use App\Models\Pembimbing;

$pesertas = Peserta::with('bidang')->get();
$penilaianData = [
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 88,
        'kerapian'      => 86,
        'kebersihan'    => 86,
        'tanggung_jawab'=> 86,
        'kerjasama'     => 87,
        'kreativitas'   => 87,
        'kejujuran'     => 86,
        'nilai_angka'   => 86.57,
    ],
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 88,
        'kerapian'      => 86,
        'kebersihan'    => 86,
        'tanggung_jawab'=> 86,
        'kerjasama'     => 87,
        'kreativitas'   => 87,
        'kejujuran'     => 86,
        'nilai_angka'   => 86.57,
    ],
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 88,
        'kerapian'      => 86,
        'kebersihan'    => 86,
        'tanggung_jawab'=> 87,
        'kerjasama'     => 88,
        'kreativitas'   => 88,
        'kejujuran'     => 87,
        'nilai_angka'   => 87.14,
    ],
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 90,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.00,
    ],
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 90,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.00,
    ],
    [
        'no_sertifikat' => '5152',
        'kedisiplinan'  => 90,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.00,
    ],
    [
        'no_sertifikat' => '7185',
        'kedisiplinan'  => 98,
        'kerapian'      => 100,
        'kebersihan'    => 100,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 100,
        'kreativitas'   => 95,
        'kejujuran'     => 100,
        'nilai_angka'   => 98.71,
    ],
    [
        'no_sertifikat' => '7188',
        'kedisiplinan'  => 92,
        'kerapian'      => 90,
        'kebersihan'    => 89,
        'tanggung_jawab'=> 91,
        'kerjasama'     => 93,
        'kreativitas'   => 88,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.43,
    ],
    [
        'no_sertifikat' => '7189',
        'kedisiplinan'  => 91,
        'kerapian'      => 90,
        'kebersihan'    => 89,
        'tanggung_jawab'=> 91,
        'kerjasama'     => 93,
        'kreativitas'   => 88,
        'kejujuran'     => 91,
        'nilai_angka'   => 90.43,
    ],
    [
        'no_sertifikat' => '7190',
        'kedisiplinan'  => 90,
        'kerapian'      => 98,
        'kebersihan'    => 96,
        'tanggung_jawab'=> 89,
        'kerjasama'     => 85,
        'kreativitas'   => 85,
        'kejujuran'     => 89,
        'nilai_angka'   => 90.29,
    ],
    [
        'no_sertifikat' => '7191',
        'kedisiplinan'  => 87,
        'kerapian'      => 88,
        'kebersihan'    => 76,
        'tanggung_jawab'=> 85,
        'kerjasama'     => 87,
        'kreativitas'   => 88,
        'kejujuran'     => 89,
        'nilai_angka'   => 85.71,
    ],
    [
        'no_sertifikat' => '7348',
        'kedisiplinan'  => 98,
        'kerapian'      => 97,
        'kebersihan'    => 98,
        'tanggung_jawab'=> 92,
        'kerjasama'     => 95,
        'kreativitas'   => 95,
        'kejujuran'     => 92,
        'nilai_angka'   => 95.29,
    ],
    [
        'no_sertifikat' => '7485',
        'kedisiplinan'  => 95,
        'kerapian'      => 93,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 94,
        'kerjasama'     => 95,
        'kreativitas'   => 95,
        'kejujuran'     => 95,
        'nilai_angka'   => 94.57,
    ],
    [
        'no_sertifikat' => '7486',
        'kedisiplinan'  => 92,
        'kerapian'      => 93,
        'kebersihan'    => 92,
        'tanggung_jawab'=> 93,
        'kerjasama'     => 95,
        'kreativitas'   => 92,
        'kejujuran'     => 93,
        'nilai_angka'   => 92.86,
    ],
    [
        'no_sertifikat' => '7487',
        'kedisiplinan'  => 95,
        'kerapian'      => 97,
        'kebersihan'    => 97,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 91,
        'kreativitas'   => 95,
        'kejujuran'     => 98,
        'nilai_angka'   => 94.71,
    ],
    [
        'no_sertifikat' => '7521',
        'kedisiplinan'  => 95,
        'kerapian'      => 93,
        'kebersihan'    => 91,
        'tanggung_jawab'=> 92,
        'kerjasama'     => 95,
        'kreativitas'   => 92,
        'kejujuran'     => 92,
        'nilai_angka'   => 92.86,
    ],
    [
        'no_sertifikat' => '8962',
        'kedisiplinan'  => 87,
        'kerapian'      => 87,
        'kebersihan'    => 88,
        'tanggung_jawab'=> 87,
        'kerjasama'     => 87,
        'kreativitas'   => 88,
        'kejujuran'     => 90,
        'nilai_angka'   => 87.71,
    ],
    [
        'no_sertifikat' => '8961',
        'kedisiplinan'  => 86,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 85,
        'kreativitas'   => 83,
        'kejujuran'     => 90,
        'nilai_angka'   => 87.71,
    ],
    [
        'no_sertifikat' => '13324',
        'kedisiplinan'  => 90,
        'kerapian'      => 86,
        'kebersihan'    => 86,
        'tanggung_jawab'=> 88,
        'kerjasama'     => 87,
        'kreativitas'   => 86,
        'kejujuran'     => 90,
        'nilai_angka'   => 87.57,
    ],
    [
        'no_sertifikat' => '13325',
        'kedisiplinan'  => 90,
        'kerapian'      => 87,
        'kebersihan'    => 88,
        'tanggung_jawab'=> 86,
        'kerjasama'     => 87,
        'kreativitas'   => 86,
        'kejujuran'     => 90,
        'nilai_angka'   => 87.71,
    ],
    [
        'no_sertifikat' => '13326',
        'kedisiplinan'  => 94,
        'kerapian'      => 90,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 94,
        'kerjasama'     => 95,
        'kreativitas'   => 90,
        'kejujuran'     => 96,
        'nilai_angka'   => 93.43,
    ],
    [
        'no_sertifikat' => '13327',
        'kedisiplinan'  => 95,
        'kerapian'      => 90,
        'kebersihan'    => 94,
        'tanggung_jawab'=> 94,
        'kerjasama'     => 95,
        'kreativitas'   => 90,
        'kejujuran'     => 96,
        'nilai_angka'   => 93.43,
    ],
    [
        'no_sertifikat' => '13328',
        'kedisiplinan'  => 98,
        'kerapian'      => 98,
        'kebersihan'    => 98,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 98,
        'kejujuran'     => 98,
        'nilai_angka'   => 98.00,
    ],
    [
        'no_sertifikat' => '14513',
        'kedisiplinan'  => 98,
        'kerapian'      => 98,
        'kebersihan'    => 98,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 98,
        'kejujuran'     => 98,
        'nilai_angka'   => 98.00,
    ],
    [
        'no_sertifikat' => '14514',
        'kedisiplinan'  => 90,
        'kerapian'      => 95,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 95,
        'kerjasama'     => 95,
        'kreativitas'   => 95,
        'kejujuran'     => 95,
        'nilai_angka'   => 94.29,
    ],
    [
        'no_sertifikat' => '14515',
        'kedisiplinan'  => 97,
        'kerapian'      => 98,
        'kebersihan'    => 96,
        'tanggung_jawab'=> 97,
        'kerjasama'     => 96,
        'kreativitas'   => 97,
        'kejujuran'     => 99,
        'nilai_angka'   => 97.14,
    ],
    [
        'no_sertifikat' => '14516',
        'kedisiplinan'  => 97,
        'kerapian'      => 98,
        'kebersihan'    => 96,
        'tanggung_jawab'=> 97,
        'kerjasama'     => 96,
        'kreativitas'   => 97,
        'kejujuran'     => 99,
        'nilai_angka'   => 97.14,
    ],
    [
        'no_sertifikat' => '14517',
        'kedisiplinan'  => 97,
        'kerapian'      => 97,
        'kebersihan'    => 97,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 97,
        'kreativitas'   => 98,
        'kejujuran'     => 97,
        'nilai_angka'   => 97.29,
    ],
    [
        'no_sertifikat' => '14518',
        'kedisiplinan'  => 98,
        'kerapian'      => 90,
        'kebersihan'    => 88,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 95,
        'kejujuran'     => 98,
        'nilai_angka'   => 95.00,
    ],
    [
        'no_sertifikat' => '14519',
        'kedisiplinan'  => 80,
        'kerapian'      => 87,
        'kebersihan'    => 85,
        'tanggung_jawab'=> 88,
        'kerjasama'     => 88,
        'kreativitas'   => 85,
        'kejujuran'     => 88,
        'nilai_angka'   => 85.86,
    ],
    [
        'no_sertifikat' => '14520',
        'kedisiplinan'  => 80,
        'kerapian'      => 87,
        'kebersihan'    => 88,
        'tanggung_jawab'=> 88,
        'kerjasama'     => 88,
        'kreativitas'   => 87,
        'kejujuran'     => 88,
        'nilai_angka'   => 86.57,
    ],
    [
        'no_sertifikat' => '14521',
        'kedisiplinan'  => 90,
        'kerapian'      => 95,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 95,
        'kerjasama'     => 90,
        'kreativitas'   => 85,
        'kejujuran'     => 90,
        'nilai_angka'   => 91.43,
    ],
    [
        'no_sertifikat' => '14522',
        'kedisiplinan'  => 90,
        'kerapian'      => 95,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 95,
        'kerjasama'     => 90,
        'kreativitas'   => 85,
        'kejujuran'     => 90,
        'nilai_angka'   => 91.43,
    ],
    [
        'no_sertifikat' => '14523',
        'kedisiplinan'  => 90,
        'kerapian'      => 95,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 95,
        'kerjasama'     => 90,
        'kreativitas'   => 85,
        'kejujuran'     => 90,
        'nilai_angka'   => 91.43,
    ],
    [
        'no_sertifikat' => '14524',
        'kedisiplinan'  => 88,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 89.71,
    ],
    [
        'no_sertifikat' => '14525',
        'kedisiplinan'  => 88,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 89.71,
    ],
    [
        'no_sertifikat' => '14526',
        'kedisiplinan'  => 88,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 89.71,
    ],
    [
        'no_sertifikat' => '14532',
        'kedisiplinan'  => 95,
        'kerapian'      => 94,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 93,
        'kerjasama'     => 90,
        'kreativitas'   => 85,
        'kejujuran'     => 90,
        'nilai_angka'   => 91.71,
    ],
    [
        'no_sertifikat' => '14533',
        'kedisiplinan'  => 95,
        'kerapian'      => 95,
        'kebersihan'    => 94,
        'tanggung_jawab'=> 91,
        'kerjasama'     => 93,
        'kreativitas'   => 85,
        'kejujuran'     => 90,
        'nilai_angka'   => 91.86,
    ],
    [
        'no_sertifikat' => '16131',
        'kedisiplinan'  => 90,
        'kerapian'      => 88,
        'kebersihan'    => 89,
        'tanggung_jawab'=> 92,
        'kerjasama'     => 93,
        'kreativitas'   => 94,
        'kejujuran'     => 95,
        'nilai_angka'   => 91.57,
    ],
    [
        'no_sertifikat' => '16148',
        'kedisiplinan'  => 97.5,
        'kerapian'      => 96.5,
        'kebersihan'    => 96,
        'tanggung_jawab'=> 97,
        'kerjasama'     => 96,
        'kreativitas'   => 96,
        'kejujuran'     => 97,
        'nilai_angka'   => 96.57,
    ],
    [
        'no_sertifikat' => '16164',
        'kedisiplinan'  => 92,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.29,
    ],
    [
        'no_sertifikat' => '16165',
        'kedisiplinan'  => 92,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.29,
    ],
    [
        'no_sertifikat' => '16166',
        'kedisiplinan'  => 92,
        'kerapian'      => 90,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 90,
        'kejujuran'     => 90,
        'nilai_angka'   => 90.29,
    ],
    [
        'no_sertifikat' => '17073',
        'kedisiplinan'  => 88,
        'kerapian'      => 90,
        'kebersihan'    => 89,
        'tanggung_jawab'=> 91,
        'kerjasama'     => 89,
        'kreativitas'   => 88,
        'kejujuran'     => 87,
        'nilai_angka'   => 88.86,
    ],
    [
        'no_sertifikat' => '17074',
        'kedisiplinan'  => 87,
        'kerapian'      => 89,
        'kebersihan'    => 91,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 89,
        'kreativitas'   => 88,
        'kejujuran'     => 88,
        'nilai_angka'   => 88.86,
    ],
    [
        'no_sertifikat' => '17075',
        'kedisiplinan'  => 95,
        'kerapian'      => 95,
        'kebersihan'    => 95,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 98,
        'kejujuran'     => 98,
        'nilai_angka'   => 96.71,
    ],
    [
        'no_sertifikat' => '17076',
        'kedisiplinan'  => 98,
        'kerapian'      => 98,
        'kebersihan'    => 98,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 98,
        'kejujuran'     => 98,
        'nilai_angka'   => 98.00,
    ],
    [
        'no_sertifikat' => '17077',
        'kedisiplinan'  => 98,
        'kerapian'      => 97,
        'kebersihan'    => 98,
        'tanggung_jawab'=> 98,
        'kerjasama'     => 98,
        'kreativitas'   => 97,
        'kejujuran'     => 98,
        'nilai_angka'   => 97.71,
    ],
    [
        'no_sertifikat' => '17961',
        'kedisiplinan'  => 89,
        'kerapian'      => 88,
        'kebersihan'    => 90,
        'tanggung_jawab'=> 90,
        'kerjasama'     => 90,
        'kreativitas'   => 84,
        'kejujuran'     => 90,
        'nilai_angka'   => 88.71,
    ],
];

// Distribute penilaian to peserta (round robin)
foreach ($pesertas as $idx => $peserta) {
    if (!isset($penilaianData[$idx % count($penilaianData)])) continue;
    $pd = $penilaianData[$idx % count($penilaianData)];
    
    // Skip if penilaian already exists
    if ($peserta->penilaian) continue;
    
    $pembimbing = $peserta->bidang_id 
        ? \App\Models\Pembimbing::where('bidang_id', $peserta->bidang_id)->first() 
        : null;
    
    Penilaian::create([
        'peserta_id'    => $peserta->id,
        'pembimbing_id' => $pembimbing?->id,
        'no_sertifikat' => $pd['no_sertifikat'],
        'kedisiplinan'  => $pd['kedisiplinan'],
        'kerapian'      => $pd['kerapian'],
        'kebersihan'    => $pd['kebersihan'],
        'tanggung_jawab'=> $pd['tanggung_jawab'],
        'kerjasama'     => $pd['kerjasama'],
        'kreativitas'   => $pd['kreativitas'],
        'kejujuran'     => $pd['kejujuran'],
        'nilai_angka'   => $pd['nilai_angka'],
    ]);
}

echo "Penilaian count: " . Penilaian::count() . PHP_EOL;
